pmmmwh/react-refresh-webpack-plugin

README.md

The instructions where missing the organisation name

Fix a typo in Yarn installation instructions

---

src/helpers/createRefreshTemplate.js
src/index.js

This fixes the plugin when the `runtimeChunks` optimization is being utilized.
We now inspect the expected bundle output filename instead of the chunk's entrypoint to make sure that we are processing a JS bundle and not something else. The previous check was not robust enough as module initializer code can be separated from the entrypoints when `runtimeChunks` is set. 
Fixes #4 
Fixes #25

fix: correctly inspect main templates to apply transform to JS runtime

---

src/helpers/createRefreshTemplate.js

This attempts to address #24 where using `window` in clean up was causing webpack to throw when using web workers and setting webpacks `config.globalObject` to `this` as is suggested by https://github.com/developit/workerize-loader and https://github.com/GoogleChromeLabs/worker-plugin
I tested this on both a standard CRA and my own app with Web Workers. Both were working with fast-refresh.  
It appears in both cases `this` correctly references window when there is a window, while for workers it references itself (and I believe the worker doesn't have `$RefreshSetup$` attached).
However, I wasn't sure in what cases cleanup is supposed to fire. So I wasn't able to test it was correctly firing still.

Use safeThis function in cleanup phase instead of "window" to better support web workers

---

README.md
src/helpers/index.js
src/helpers/injectRefreshEntry.js
src/helpers/validateOptions.js
src/index.js
src/runtime/globals.js
src/runtime/utils.js
src/types.js

It has been a while since the last release, and a lot of opinion have been brought up related to the error overlay integration. This PR aims to address most of them, whether it is to not use it, or use some tool-dependent ones.
```ts
interface ErrorOverlayOptions {
/* The module you want to use as an error overlay. */
module: string;
/* The module you want to use as an entry point to set up the error overlay. */
entry?: string;
}
```
Read [README.md](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/feat/customize-overlay/README.md) for a better explanation since there some caveats related to this approach.
Fixes #28
Partially addresses #7
Supersedes #33 #41
Related facebook/create-react-app#8582
CC @gaearon @blainekasten @ianschmitz @Timer
Would love your thoughts as framework …

feat(overlay): allow full customization of the error overlay integration

---

src/runtime/ErrorOverlayEntry.js

This fixes the issue mentioned in #52, where build warnings are preventing the overlay to be dismissed after successfully clearing build errors.
Handling for warnings still have to be implemented, and would probably benefit from a warnings overlay, but this is a quick fix to get stuff working first.

fix: allow overlay to dismiss on build with warnings

---

src/index.js
src/overlay/index.js

This fixes a missed case when `false` will be provided to `webpack.ProvidePlugin`, which causes issues in error overlay call sites.
Fixes #56

fix: make optional overlay runtime truely optional

---

README.md
package.json
src/runtime/createSocket.js

This switches to the `native-url` module instead of the polyfilled `node-url` module (automatically done by Webpack 4, but will be removed in Webpack 5 and non-browser environments).
This will break IE11.
Fixes #42

fix: use native-url instead of node's url for compat

---

src/helpers/defaults.js
src/helpers/validateOptions.js

This adds stricter validation to options - basically we will now throw if the received options are malformed.

feat: make options validation stricter

---

src/helpers/injectRefreshEntry.js
src/helpers/validateOptions.js
src/runtime/ErrorOverlayEntry.js
src/types.js

This moves `sockHost`, `sockPath` and `sockPort` under the `overlay` option - because they do only affect that part of the integration.
This also includes part a fix that will prevent race-conditions from occurring (Ref #49), because now error overlay entries are only appended as the last entry in the chain.

fix: scope socket options

---

src/helpers/defaults.js

This adds back the default value for `sockIntegration` in `options.overlay`.
Fixes #68

fix: add missing sock integration default

---

package.json

types can't be found automatically if they're not at `index.d.ts` at the root of the module, we need to specify the path manually

fix: add path to types to package.json

---

package.json

This PR fixes #95. The symlink is only needed for tests, so switching to a pretest command will work for package development as well as maintaining compatibility with consumers' projects.

chore: use pretest instead of postinstall for compat with yarn v2

---

src/overlay/components/CompileErrorTrace.js
src/overlay/index.js
src/runtime/ErrorOverlayEntry.js
src/runtime/formatWebpackErrors.js
src/runtime/refreshUtils.js

I have the unfortunate need to support IE11, so I noticed some places that were using non-ES5 features. 
I've tested on v0.3.1 and can confirm that IE11 works with these changes (and the polyfill provided in the readme).

fix: remove all ES6 syntax

---

jest.config.js
package.json

This PR moves to use `jest-circus` as test runner as it will be default in upcoming Jest 27.

test: use jest-circus as test runner

---

.circleci/config.yml
.eslintignore
.eslintrc.json
.prettierignore
package.json

This adds lint/format checks on CI, reducing unwanted formatting noise in PRs.

ci: run lint/format jobs

---

src/runtime/refreshUtils.js

This PR removes the `Refresh.hasUnrecoverableErrors` check on module dispose as the function will always return false now, and will be removed in the future.
Ref: [Implementation](https://github.com/facebook/react/blob/6d375f3078b6b58afb9c07dce3c5144344d8d3de/packages/react-refresh/src/ReactFreshRuntime.js#L566-L569)
Related to #79 - removes the need for `window.location`.

chore: remove unrecoverableErrors check as there are none now

---

.eslintrc.json
src/index.js
src/loader/RefreshModule.runtime.js
src/loader/index.js
src/runtime/refreshUtils.js

In #79 a bug was found where `__react_refresh_utils__` is `undefined` when using custom error overlay entries. It seems that we've hit a limitation of `webpack.ProvidePlugin` - injected modules will not contain references to other modules that are injected together.
This PR fixes that by excluding these modules from loader processing - one caveat is user-provided relative imports within `options.overlay.module` will also have to be excluded due to how module resolution works. This is a bit of a workaround but since the API is more of an advanced feature I think we can further polish it later.
Loader source map generation (when the loader is first in the chain) is also fixed here.

fix: handle dependency clashes with injected modules

---

src/runtime/refreshUtils.js

noticed this when using ie 11, first PR so let me know if it is ok

Shorthand property names not supported in ie11

---

.circleci/config.yml
package.json
scripts/test.js

This PR adds test reporting and ties to make tests run in parallel by timings to speed them up.

ci: add junit reporter and parallelism for tests

---

lib/utils/injectRefreshLoader.js

This fix ensures injected dependencies via loaders will get picked up and wrapped/processed by whatever transform is coming next (Babel/TS/etc). This is important in some scenarios (e.g. dependency-related helpers with caching behaviour) and will help maintain referential equality across hot updates for the "family" reference generated by `react-refresh/runtime`. This also makes sure when dependencies are being mangled/wrapped in other loaders, our injected ones will be processed too, so it ensures that only on version of a dependency can be used.
Fixes #120

fix: make sure injected imports will be processed by whatever comes next

---

lib/index.js
loader/RefreshModule.runtime.js
test/loader/loader.test.js

This is related to #126.
This PR acknowledges Webpack@5 that we depend on the module interceptor runtime global (well - in most cases it should have been declared by the HMR plugin).

fix: add needed runtimeRequirements for refresh runtime module

---

lib/index.js
lib/runtime/RefreshRuntimeModule.js
lib/utils/getRefreshGlobal.js
lib/utils/injectRefreshLoader.js
test/unit/getRefreshGlobal.test.js

This PR fixes most of the issues that was a result of #129.
An underlying issue was that Babel-injected helpers were calling the parent module's `refresh.cleanup` function, thus breaking the encapsulation of the refresh runtime and led to nondeterministic behaviour. A expplicit `init` step is added to the runtime global to ensure that each module can only call it's own cleanup function.
Fixes #120 
Fixes #136 
Fixes #138

fix: runtime injection issues

---

client/ErrorOverlayEntry.js

This is a work-around to make apps build for #143.
In the future, we might add an API to allow customizing the entry injection behaviour.

fix: only inject overlay in development mode and when window is defined

---

README.md
lib/options.json
lib/types.js
lib/utils/injectRefreshEntry.js
lib/utils/normalizeOptions.js
test/unit/injectRefreshEntry.test.js
test/unit/normalizeOptions.test.js
test/unit/validateOptions.test.js

This PR moves the `useLegacyWDSSockets` option to where it belongs (i.e. is being used).
This is a breaking change but the impact should be minimal.

refactor!: scope `useLegacyWDSSockets` under `overlay`

---

README.md
lib/index.js
lib/options.json
lib/types.js
lib/utils/injectRefreshEntry.js
test/unit/normalizeOptions.test.js
test/unit/validateOptions.test.js
types/types.d.ts

This change is born to support CRA - they have a custom entry integration which does not hook up with the plugin, but could benefit with an integrated error overlay module.
The corresponding changes to CRA will be PRed later, when 0.4.0 is released (SOON!)

fix: allow false as values to required overlay options

---

lib/index.js

This moves plugin's HMR detection from detecting the plugin before compile to checking the actual hot context flag injected by the plugin.
The previous check was problematic because the HMR plugin in some cases are not initiated by the user - and when that happens, it will not be available in the `options.plugins` array, yielding 100% false negatives.
Fixes #158

fix: detect HMR context rather than the plugin

---

lib/index.js
lib/runtime/RefreshUtils.js
lib/utils/createError.js
lib/utils/index.js
lib/utils/injectRefreshEntry.js
sockets/utils/getCurrentScriptSource.js
test/unit/injectRefreshEntry.test.js

This PR unifies and adds a prefix to all errors we throw to better direct users at what is wrong (maybe it is not us :P).

refactor: add createError utility to generate scoped error messages

---

examples/create-react-app/.env
examples/create-react-app/package.json
examples/create-react-app/yarn.lock

This is to address #157 - CRA pins their Webpack version to 4.42.0 but 0.4.0 requires 4.43.0.

fix: pin webpack version for CRA example to make things compile

---

lib/runtime/RefreshUtils.js
overlay/index.js
overlay/utils/debounce.js
package.json
yarn.lock

In #159 there was concern raised in the usage of modular lodash packages, since they will be deprecated in lodash v5.
This PR addresses that concern by moving from `lodash.debounce` to our custom implementation.
Fixes #159

refactor: remove lodash.debounce and use custom impl instead

---

client/utils/formatWebpackErrors.js
lib/runtime/RefreshUtils.js
loader/index.js
test/jest-test-setup.js

Since Webpack 5 changes how compilation stats for `errors` and `warnings` are emitted (as an object instead of a concatenated string), we need to update our error formatter to allow errors to be displayed correctly.
**Before**
**After**

feat: correctly format compilation errors for Webpack 5

---

lib/utils/injectRefreshEntry.js
test/unit/injectRefreshEntry.test.js

First of all: hi @pmmmwh and thanks a lot for your work in making it easy to bring react-refresh to webpack based projects. 👏  
In some of the projects I am currently working on, the bundles are loaded from a regional CDN, and thus we need to rely on a dynamic webpack public path.
```js
// in set-env.js file
__webpack_public_path__ = `https://${cdnDomain}/my-assets-path/`;
```
I found that, for HMR  - in this case based on `webpack-hot-middleware` - to work appropriately with a dynamic webpack public path one has to inject an entry that defines the dynamic public path prior to the socket entry:
```js
// in webpack.config.js
...
entry: {
app: [
'./src/set-env.js',
'webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true',
'./src/app.js'
]
}
...
```
When I added …

Keep array-based entries relative-order during injectRefreshEntry

---

.circleci/config.yml
README.md

This PR switches CI to run on a custom built Node.js image for Puppeteer tests - which yields a ~5 minute speed up in our CI times.
I've also dropped tests for Node.js 13 as it has reached EOL.

ci: try using new puppeteer image

---

examples/create-react-app/config-overrides.js

I was trying to use the example for `create-react-app` (< v4) but was seeing this build error:
```sh
yarn run v1.22.4
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.
./src/index.js
Error: [BABEL] /Users/aaron/Projects/react-refresh-webpack-plugin/examples/create-react-app/src/index.js: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "production". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "/Users/aaron/Projects/react-refresh-webpack-plugin/examples/create-react-app/node_modules/react-refresh/babel.js")
at Generator.next (<anonymous>)
at Generator.next (<anonymous>)
error Command failed with exit code 1.
info Visit …
```

Enable react-refresh plugins only in development

---

examples/typescript-without-babel/package.json
examples/typescript-without-babel/webpack.config.js
examples/typescript-without-babel/yarn.lock

As mentioned in https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/46#issuecomment-678902720 . `awesome-typescript-loader` has been archived. So `ts-loader`.
Tried demo and it's not breaking.

use ts-loader in typescript example, upgrade deps

---

README.md
docs/API.md
docs/TROUBLESHOOTING.md

This is a rewrite of the existing documentation, aiming to provide clearer/more detailed explanation on how this plugin works as well as less bias towards `webpack-dev-server` (since we support WHM/WPS now).

docs: rewrite documentation

---

loader/index.js

This fixes #192 with a patch around mozilla/source-map#349.

fix: patch around loader crashes when global fetch polyfills are used

---

lib/utils/normalizeOptions.js
test/unit/normalizeOptions.test.js

This is an overlook that just happen to not affect anyone - the default behaviour (and the documentation) does imply that files are matched case-insensitively.

fix: set default file matchers to be case insensitive

---

docs/TROUBLESHOOTING.md

This is an addendum to #189 - which just adds a note on RHL because the two packages cannot be used together.

docs: add note for conversion from react hot loader

---

.circleci/config.yml

This bumps CI to use latest Node 14 release (14.11).

ci: bump node 14 image version

---

package.json

chore(deps-peer): relax peer dependency on type-fest

---

client/ErrorOverlayEntry.js
client/ReactRefreshEntry.js
docs/API.md
docs/TROUBLESHOOTING.md
lib/globals.js
lib/index.js
lib/options.json
lib/types.js
lib/utils/normalizeOptions.js
test/unit/normalizeOptions.test.js
test/unit/validateOptions.test.js
types/types.d.ts

This PR implements a compatibility layer to allow multiple instances of React/React-Refresh to run simultaneously. Another layer of compatibility is added to the overlay to make sure only the first injection would happen (since it is global).
~**TODO: Documentation**~
Fixes #139
Fixes #239
Fixes #250

feat: implement monorepo compatibility layer with library

---

lib/index.js
package.json
yarn.lock

**BREAKING CHANGE**
- Bumped minimum Node.js version to `10.13` (first LTS of the Node.js 10 line)
- Bumped `native-url` to `0.3.x`
- Bumped `schema-utils` to `3.x.x`

chore(deps): bump package dependencies

---

client/ErrorOverlayEntry.js
client/LegacyWDSSocketEntry.js
client/utils/patchUrl.js
docs/API.md
docs/TROUBLESHOOTING.md
lib/index.js
lib/options.json
lib/types.js
lib/utils/normalizeOptions.js
package.json
test/unit/normalizeOptions.test.js
test/unit/validateOptions.test.js
types/types.d.ts
yarn.lock

This PR adds out of the box pony-filling capabilities for the DOM URL API.

feat: automatic DOM URL ponyfilling

---

lib/types.js
lib/utils/normalizeOptions.js
test/unit/normalizeOptions.test.js
types/types.d.ts

This is a breaking change - but the option have been long deprecated since the `0.3.0` release and in practice shouldn't affect users since it is a no-op.

refactor!: remove disableRefreshCheck option

---

lib/options.json
test/unit/validateOptions.test.js

Fixes #280
This capability is particularly useful if you want to provide a package per se.

fix: accept non-absolute paths to support package use cases

---

sockets/WHMEventSource.js

fix: remove usage of property shorthands for IE11

---

lib/index.js
lib/runtime/RefreshRuntimeModule.js
lib/utils/getRefreshGlobal.js
loader/RefreshSetup.runtime.js
test/loader/loader.test.js
test/unit/getRefreshGlobal.test.js

The previous implementation would have side-effects when a non-processed require pop up within the module, effectively causing runtime to be cleaned before the module have finished executing. As a result some parts of the update chain became unbound and causes bailouts that shouldn't happen.
To fix this, the `init` and `setup` stages are consolidated into one, which will trigger on **EVERY** call to `__webpack_require__`, setting boundaries for all helpers and also ensures all fields on the refresh global would be properly restored after the module's execution.
*TODO: Test cases to ensure the behaviour by mocking Webpack's main template*
Fixes #260 
Fixes #287 
Fixes #314

fix: ensure refresh runtime init is stable across module boundaries

---

lib/utils/injectRefreshEntry.js
test/unit/injectRefreshEntry.test.js

This fixes issues where the plugin would silently fail when users are using zero-config Webpack setups (where we will receive an object in the format of `{ main: {} }`). It will now throw and point the user to specify their entry object - so we do not need to do guess work on how to inject our entries.
Fixes #293
Fixes #303

fix: correctly throw when an ambiguous entry is received

---

sockets/utils/getCurrentScriptSource.js

The current implementation of `getCurrentScriptSource` will fail when there are scripts without `src` used in the document and the script that runs React app is not the last script in the document.
For example, in the case when there are other 3rd party script snippets such as Qualtrics used in the document, the last script get by the original implementation could be such script and the `src` will be null. As a result, `getCurrentScriptSource` will return `null` and `getSocketUrlParts` will fail at `url.parse(scriptSource || '')`.
To fix this issue, we could return the last script that HAS `src` attribute as the current script.

fix: fix getCurrentScriptSource to handle scripts without src

---

sockets/utils/getSocketUrlParts.js
test/mocks/location.js
test/unit/getSocketUrlParts.test.js

This migrates from using `url.parse` from `native-url` to actually just using the WHATWG URL API which handles both path-relative and protocol-relative URLs gracefully.
CC @nticaric
Fixes #323

fix: re-implement URL parsing with WHATWG URL API

---

README.md
examples/typescript-without-babel/package.json
examples/typescript-without-babel/webpack.config.js
examples/typescript-without-babel/yarn.lock

Add react-refresh-typescript to documentation

---

lib/utils/getRefreshGlobal.js
test/unit/getRefreshGlobal.test.js

Fixes #325
The linked issue is an unsupported pattern, but due to the nature of the Babel transform unwanted calls to the register/signature functions might happen in edge cases.
This PR ensures there's a global safety net (using function stubs) so they wouldn't crash the app during HMR runtime.

fix: ensure global stubs on runtime and signature functions

---

lib/utils/injectRefreshLoader.js

Fixes #324
Since `RuntimeUtils` has `react-refresh/runtime` as a dependency, it is also not safe to allow any processing on that package.
This PR ensures even if the user specifies `node_modules` to be processed, the plugin wouldn't crash the runtime due to cyclic imports.

fix: prevent runtime self-referencing via react-refresh

---

package.json

This package [requires webpack-dev-server@3.x || 4.x](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/package.json#L111), `@symfony/webpack-encore` [requires webpack-dev-server@^4.0.0-beta.0](https://github.com/symfony/webpack-encore/blob/v1.1.2/package.json#L50). This creates a conflict as the version constraint of 4.x does not encompass beta versions.
I believe the version should be as specified in this PR as there is no stable version 4.x yet.

Update package.json for webpack-dev-server beta support

---

lib/RefreshRuntimeModule.js
lib/index.js

Fixes #341
Declares everything we need in `runtimeRequirements` to ensure we don't get dropped, for example, after a HMR update.

fix: ensure refreshGlobal is marked in runtime requirements

---

sockets/utils/getSocketUrlParts.js
test/unit/getSocketUrlParts.test.js

Originally proposed in #332
This PR removes obsolete (and inapplicable, non-documented) port `0` handling in socket URL parsing.

refactor!: cleanup socket url logic to remove obsolete stuff

---

lib/utils/injectRefreshLoader.js

This was caused by a fix introduced in #370 which is supposed to fix #324 - however the test was not specific enough and would break any app that includes the text `react-refresh`.
To workaround that, a require-based approach is used now to prevent the issue while maintaining the behaviour of not crashing even if the whole `node_modules` is marked to be processed by the plugin.
Fixes #379

fix: properly test for react-refresh imports

---

package.json
sockets/WDSSocket.js
sockets/utils/getSocketUrlParts.js
sockets/utils/getUrlFromParts.js
test/unit/getUrlFromParts.test.js
yarn.lock

Fixes #288 
This drops our dependency on `native-url` in favour of a constrained URL creation from parts (since we control the parsing).

feat!: implement constrained get URL from parts

---

sockets/WDSSocket.js
sockets/utils/getUrlFromParts.js
test/unit/getUrlFromParts.test.js

Fixes #391
WDS v4 beta 3 a breaking change was introduced to by default use WS client - and having this configured by default would also benefit people opting in to use WS even on WDS v3.

feat: automatically override ws when wds use websockets

---

client/ErrorOverlayEntry.js

Setting the `overlay` property to `false` in the plugin options blows up when loading the page. The following error message is displayed in the latest beta release (0.5.0-beta.4, same issue is present in 0.4.3):
Checking if `__react_refresh_socket__` is truth-y does the trick. `__react_refresh_socket__` is set to false when the overlay is disabled (see [lib/index.js#L101](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/lib/index.js#L101)).

fix: prevent overlay code from running if disabled

---

lib/index.js
lib/utils/getAdditionalEntries.js
lib/utils/getIntegrationEntry.js
lib/utils/index.js
lib/utils/injectRefreshEntry.js
test/unit/injectRefreshEntry.test.js
yarn.lock

Fixes #293 
Fixes #303 
Fixes #346 
Fixes #398

feat: use entry hooks for injection in Webpack 5

---

package.json
yarn.lock

Fixes #411 
In theory this is not a bug at all because Webpack v5 ships its own types and we don't depend on anything out of what is shipped, but because of `npm@7` by default would crash on peer dependencies even though it is an entirely optional one, we have to relax it so people on newer types could install without crashing.

chore: relax webpack types to allow v5

---

lib/index.js

fix: handle case when dep.request is undefined

---

client/ErrorOverlayEntry.js
client/utils/retry.js

Fixes #422 - proper socket setup will require changes in Gatsby's Webpack setup.

feat: initialise socket with exponential retry

---

package.json
yarn.lock

npm 7 throws an error when installing packages if the versions of peerDependencies are not compatible.
Since type-fest is a utility package, you will likely use many versions, so you should include as many versions as possible to avoid breaking DX.
Now, this package uses only Except, SetRequired, and LiteralUnion in type-fest, so it is expected to work normally in 0.17.0 or later.
https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies
https://github.com/sindresorhus/type-fest/releases/tag/v0.6.0
https://github.com/sindresorhus/type-fest/releases/tag/v0.8.0
https://github.com/sindresorhus/type-fest/releases/tag/v0.17.0

chore: update type-fest version

---

overlay/components/CompileErrorTrace.js
package.json
yarn.lock

This fixes the ReDoS vulnerability [CVE-2021-23424](https://github.com/advisories/GHSA-whgm-jr23-g3j9).
See: https://github.com/Tjatse/ansi-html/issues/19#issuecomment-913119841

fix: replace ansi-html with ansi-html-community

---

lib/utils/getRefreshGlobal.js
test/unit/getRefreshGlobal.test.js
test/unit/makeRefreshRuntimeModule.test.js

Fixes #455
Fixes #489
By not using the signature function directly but instead making it a function returning that value fixes the case where the referential identity of the function is not updated even though the underlying runtime have been patched.

fix: ensure signature function don't share identity with stubs

---

package.json

https://github.com/sindresorhus/type-fest/releases/tag/v2.0.0
type-fest is 2.0 and there is no problem with compatibility, so bump

Bump type-fest in peerDependencies

---

lib/utils/getAdditionalEntries.js
test/unit/getAdditionalEntries.test.js

feat: add support for WDS client.webSocketURL

---

.gitignore
loader/index.js

This fixes a memory leak in the loader when source map generation is required - it will now properly cleanup instances of `SourceMapConsumer` and maintain decent performance when the number of files increases.
Fixes #255 
Fixes #524 
Fixes #536

perf: fix loader memory leak from non-destroyed source map consumers

---

overlay/components/PageHeader.js
overlay/components/RuntimeErrorFooter.js
overlay/index.js

When website on which overlay is displayed uses `viewport-fit: cover`, website declares it will handle unsafe areas on its own. This also applies to the overlay displayed on top of it.
Before:
After:

Fix paddings not taking unsafe area into account

---

lib/utils/injectRefreshLoader.js

Sometimes, we may want to include some js files as-is by writing some code like:
```
loadScript(new URL('./vendor.js', import.meta.url).toString())
```
In this case, injecting runtime code cause that file to be broken. We should exclude all asset modules from being injected.

feat: exclude files that referenced as assets

---

client/ReactRefreshEntry.js
loader/index.js
sockets/WPSSocket.js
test/jest-resolver.js
test/loader/loader.test.js
test/loader/unit/getRefreshModuleRuntime.test.js
test/unit/getRefreshGlobal.test.js
test/unit/makeRefreshRuntimeModule.test.js
yarn.lock

fix: import react-refresh without depending on extension

---

README.md

This commit removes the out-of-place word "integrate".
An alternative is:
```
For most setups, we recommend integrating with `babel-loader`.
```
:wave: Hello! This was a bit of a fly-by as I was reading the README. Thanks :tada:

docs: fix typo in README - Usage

---

examples/flow-with-babel/src/index.js
examples/typescript-with-babel/src/index.tsx
examples/typescript-with-swc/src/index.tsx
examples/typescript-with-tsc/src/index.tsx
examples/webpack-dev-server/src/index.js
examples/webpack-hot-middleware/src/index.js
examples/webpack-plugin-serve/src/index.js

> ReactDOM.render is no longer supported in React 18. Use createRoot instead.
Source: [React 18 upgrade guide](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis)

Replace deprecated ReactDOM.render with Root.render in examples.

---

docs/API.md
sockets/utils/getCurrentScriptSource.js

fix: make current script detection more robust on edge cases

---

lib/utils/injectRefreshLoader.js

After investigating some performance issues that only appear when enabling this plugin, I discovered that the `require.resolve('react-refresh')` which gets called in `injectRefreshLoader` seems to be the cause.
Moving the call outside the `injectRefreshLoader` cuts initial compile time in more than half (~40s -> ~15s) and incremental compile time has a similar speedup (~8s -> ~3s).
I don't know why, but I guess the require.resolve is not cached for some reason, or just takes some time, which adds up when the function runs for thousands of modules?
The change moving the `refreshUtilsPath` outside the function is not required to improve the performance, but I don't see why it wouldn't be moved outside the function as it should be static.
Tested on two different machines running the same …

Fix injectRefreshLoader performance issue

---

docs/TROUBLESHOOTING.md
package.json
yarn.lock

chore: misc changes

---

lib/runtime/RefreshUtils.js

When fast-refreshing the following code:
```tsx
const DATA = Array.from({ length: 100000 }, (_, i) => Math.random());
export const App = () => {
return (
<div>
<div>REWRITE_HERE</div>
<div>{DATA.length}</div>
</div>
);
};
```
each refresh will not purge the previous DATA since we chain `prevExports`, which references `App`, which closes over `DATA`.  For reproducible example and more detailed explanation, please check https://github.com/naruaway-sandbox/fast-refresh-hmr-memory-leak-demo
Historical list of DATA is retained like the following via prevExports:
This PR breaks the chain by only passing absolutely necessary data across fast-refreshes, which is `signature: string[]` and `isReactRefreshBoundary: boolean`. So it will be impossible to accidentally form this kind of reference chain. …

fix: Avoid unnecessary memory leaks due to prevExports

---

lib/utils/injectRefreshLoader.js

fix: allow exclusion of dynamically generated modules

---

docs/API.md

It''s `clearCompileError` https://github.com/search?q=repo%3Apmmmwh%2Freact-refresh-webpack-plugin+clearCompileError&type=code, not `clearCompileErrors` https://github.com/search?q=repo%3Apmmmwh%2Freact-refresh-webpack-plugin+clearCompileErrors&type=code.

Fix typo in API.md (clearCompileErrors -> clearCompileError)

---

.circleci/config.yml
package.json
scripts/test.js
test/helpers/sandbox/aliasLegacyWebpack.js
test/helpers/sandbox/aliasLegacyWebpackDevServer.js
test/helpers/sandbox/aliasWDSv3.js
test/helpers/sandbox/aliasWDSv4.js
test/helpers/sandbox/aliasWebpackv4.js
test/helpers/sandbox/configs.js
test/helpers/sandbox/spawn.js
test/jest-environment.js
yarn.lock

Fixes https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/787
Fixes https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/800
Fixes https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/824
Fixes #836

chore: support WDS v5

---

examples/webpack-hot-middleware/server.js

To handle the routes on the client, if the user forces the URL on the client side, Express will send the React app to the front-end, and then the application can handle the route in the front-end.

To handle the routes on the client

---

.gitignore
CHANGELOG.md
docs/TROUBLESHOOTING.md
package.json
webpack.config.js

Partially Fixes #42 
Fixes #743
Fixes #745 
Fixes #765 
Fixes #833

feat: build thin externalization client

---

client/ErrorOverlayEntry.js
client/ReactRefreshEntry.js

fix: make plugin entries empty for production

---

lib/utils/makeRefreshRuntimeModule.js
test/unit/makeRefreshRuntimeModule.test.js

#729 happens because webpack's Top Level Await implementation allows for modules to be loaded in parallel. This breaks the assumption that a global `__webpack_require__.$Refresh$`, which contains information about the currently loading module, can be managed as a stack like data structure.
This change borrows the concept from webpack's own `webpack/runtime/hot module replacement` chunk that each module can receive its own copy of a "proxy" `__webpack_require__`. This proxy delegates all of its behavior to the global `__webpack_require__` except for access to the `$Refresh$` property. In practice this guarantees that `__webpack_require__.$Refresh$` is isolated to the currently loading module, avoiding any chance of a race condition caused by parallel loading.
This has been found to solve …

fix: out of order cleanup with top-level await
