pmmmwh/react-refresh-webpack-plugin

src/index.js
The changes here makes it so that `__react_refresh_error_overlay__` will be defined even the option is `false` (ProvidePlugin does not work with non-path values), and ensure the branched `__react_refresh_error_overlay__` calls will be erased on build.
Fixes #70
=> fix: stub errorOverlay module when the option is false

src/loader/index.js
Pretty straightforward change :)
Fixes #67
=> remove check for "react" import

package.json, src/helpers/getSocketIntegration.js, src/helpers/injectRefreshEntry.js, src/helpers/validateOptions.js, src/index.js, src/loader/index.js, src/overlay/index.js, src/overlay/utils/removeAllChildren.js, src/runtime/errorEventHandlers.js, src/types.js, tsconfig.json, types/index.d.ts, types/types.d.ts
This PR utilizes the TypeScript feature to generate types from JSDoc comments.
Whether to check in the generated files or not is yet to be decided.
Fixes #55
=> feat: generate type files from JSDoc

src/options.json
This one addresses #77
Fixes #77
=> Fixed socket option validaiton

src/helpers/injectRefreshEntry.js
This PR adds logic to allow socket-integration-related Webpack entries to run before the error overlay entry, while keeping the error overlay entry before any user code is ran. This fixes the missing error overlay when the app crashes on first load (because user code would crash, and that would result in skipped execution for error overlay code).
=> fix: defer error overlay entry injection to after socket init

src/overlay/components/RuntimeErrorStack.js
=> fix: handle failure to parse error stack traces

examples/create-react-app/package.json, examples/create-react-app/yarn.lock, examples/flow-with-babel/package.json, examples/flow-with-babel/yarn.lock, examples/typescript-without-babel/package.json, examples/typescript-without-babel/yarn.lock, examples/webpack-dev-server/package.json, examples/webpack-dev-server/yarn.lock, examples/webpack-hot-middleware/package.json, examples/webpack-hot-middleware/yarn.lock, examples/webpack-plugin-serve/package.json, examples/webpack-plugin-serve/yarn.lock
Just to please the Dependabot gods 🦄
=> chore(deps-dev): bump dependencies for example apps

lib/index.js
=> fix: a typo at webpack 5 NormalModule require

lib/globals.js, lib/index.js
fix https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/232
=> add webpackrequire requirement

README.md, docs/TROUBLESHOOTING.md
=> docs: add a note on wds v3 and webpack 5 browserslist

docs/API.md, docs/TROUBLESHOOTING.md, lib/index.js, lib/utils/getAdditionalEntries.js
This addresses main compatibility coverage issues with Webpack 5 and the new WDS 4 beta.
Fixes #264
=> chore: miscellaneous fixes for webpack 5 and wds 4

docs/TROUBLESHOOTING.md
remove unnecessary `$` sign in line 61
=> fix the sloppy `Uncaught ReferenceError: $RefreshReg$ is not defined` troubleshoot suggestion 

loader/RefreshModule.runtime.js, test/helpers/sandbox/index.js, test/loader/loader.test.js
=> fix: call invalidate for non boundary updates for consistency

package.json
Since we started supporting wds 4 in [this PR](https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/286), it should be reflected in the dependency as well.
=> Update wds version

package.json, yarn.lock
Fixes #266
Fixes #301
Fixes #315
Fixes #316
Fixes #340
=> chore(deps)!: bump react-refresh to 0.10.0

package.json
=> fix: add options to files

docs/API.md, docs/TROUBLESHOOTING.md
This adds more cases to troubleshooting that was raised in issues, and showcases the reset directive.
=> docs: misc updates to documentation [skip ci]

sockets/WDSSocket.js
Fixes an issue reported in #278.
=> fix: check socket client name to be non-null-ish

client/ErrorOverlayEntry.js, client/utils/patchUrl.cjs, lib/utils/makeRefreshRuntimeModule.js, test/unit/makeRefreshRuntimeModule.test.js
=> fix: patch IE11 compat for URL polyfilling and TLA

.eslintrc.json, client/ErrorOverlayEntry.js, client/LegacyWDSSocketEntry.js, client/ReactRefreshEntry.js, client/utils/errorEventHandlers.js, client/utils/formatWebpackErrors.js, client/utils/retry.js, overlay/components/CompileErrorTrace.js, overlay/components/PageHeader.js, overlay/components/RuntimeErrorFooter.js, overlay/components/RuntimeErrorHeader.js, overlay/components/RuntimeErrorStack.js, overlay/components/Spacer.js, overlay/containers/CompileErrorContainer.js, overlay/containers/RuntimeErrorContainer.js, overlay/index.js, overlay/theme.js, overlay/utils.js, package.json, sockets/WDSSocket.js, sockets/WHMEventSource.js, sockets/WPSSocket.js, sockets/utils/getCurrentScriptSource.js, sockets/utils/getSocketUrlParts.js, sockets/utils/getUrlFromParts.js, sockets/utils/parseQuery.js, yarn.lock
=> fix: revert ESM imports/exports to cater CJS workflows

overlay/components/CompileErrorTrace.js
=> fix: only format compile error message if the parts has length

sockets/WDSSocket.js
=> fix: handle ESM socket clients from WDS

README.md
=> docs: make Webpack 5 compat explicit

client/package.json, loader/utils/getModuleSystem.js, overlay/package.json, package.json, sockets/package.json, test/loader/unit/getModuleSystem.test.js, yarn.lock
This handles the monorepo story of ESM.
Fixes #294
Fixes #445
=> fix: resolve module system upwards from resource path

lib/utils/makeRefreshRuntimeModule.js, test/unit/makeRefreshRuntimeModule.test.js
=> fix: ensure async modules would wait for cleanup before progressing

client/ErrorOverlayEntry.js, overlay/components/CompileErrorTrace.js, overlay/components/RuntimeErrorStack.js, overlay/index.js
=> fix: remove usage of destructuring for IE11 compat

README.md, examples/flow-with-babel/package.json, examples/flow-with-babel/src/App.jsx, examples/flow-with-babel/src/ArrowFunction.jsx, examples/flow-with-babel/yarn.lock, examples/typescript-with-swc/package.json, examples/typescript-with-swc/src/App.tsx, examples/typescript-with-swc/src/ArrowFunction.tsx, examples/typescript-with-swc/webpack.config.js, examples/typescript-with-swc/yarn.lock, examples/typescript-with-tsc/package.json, examples/typescript-with-tsc/src/App.tsx, examples/typescript-with-tsc/src/ArrowFunction.tsx, examples/typescript-with-tsc/yarn.lock, examples/webpack-dev-server/package.json, examples/webpack-dev-server/src/App.jsx, examples/webpack-dev-server/src/ArrowFunction.jsx, examples/webpack-dev-server/yarn.lock, examples/webpack-hot-middleware/src/App.jsx, examples/webpack-hot-middleware/src/ArrowFunction.jsx, examples/webpack-plugin-serve/src/App.jsx, examples/webpack-plugin-serve/src/ArrowFunction.jsx
=> chore: bump swc and webpack-dev-server for examples

package.json, yarn.lock
=> chore: bump react refresh to 0.11.0

client/utils/retry.js, lib/runtime/RefreshUtils.js
=> fix: gracefully handle failed capture of exports

lib/runtime/RefreshUtils.js
Fixes #245 - in particular with systems that dynamically generates modules (e.g. Linaria).
=> fix: add special handling for unavailable moduleId

README.md
=> docs: update README to reflect the latest API changes [skip ci]

lib/utils/getAdditionalEntries.js, test/unit/getAdditionalEntries.test.js
=> fix: handle WDS auto port values

overlay/components/CompileErrorTrace.js
=> fix: ensure compile error is parsed correctly

lib/utils/injectRefreshLoader.js
=> fix: make loader injection respect virtual modules

sockets/utils/getSocketUrlParts.js, test/sockets/getSocketUrlParts.test.js
=> fix: port for WDS should be optional

.circleci/config.yml, package.json, yarn.lock
=> chore: bump dependencies and tested node versions

.prettierrc, client/utils/retry.js, package.json, yarn.lock
=> chore: bump deps

loader/index.js, loader/utils/getModuleSystem.js, test/loader/loader.test.js
=> fix: get module system scoped to context

package.json, yarn.lock
=> chore: move to yalc-less test infra

README.md
=> docs: clarify minimum supported Node.js version 

lib/utils/makeRefreshRuntimeModule.js, test/unit/makeRefreshRuntimeModule.test.js
=> fix: ensure `this` propagates through module execution interceptor

CHANGELOG.md
=> docs: link to PRs from changelog
